apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
      version: '*'
  install: {}
  interval: 30s
  targetNamespace: flux-staging
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: 2.9.17
    ingress:
      host: staging.devops-toolkit.192.168.64.3.nip.io